name: personality
channels:
  - conda-forge
dependencies:
  - numpy=1.22.3
  - python=3.9.12
  - readline=8.1
  - scipy=1.8.1
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - tornado=6.1
  - typing=3.10.0.0
  - typing_extensions=4.2.0
  - pip:
    - huggingface-hub==0.11.1
    - jsonlines==4.0.0
    - openai==1.2.4
    - pandas==1.4.2
    - pandas-stubs==1.2.0.58
    - pip==22.1
    - tqdm==4.64.0
    - transformers==4.25.1
